spring:
  application:
    name: encoding-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: encoding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.streamvault.encodingService.event.VideoUploadedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

# AWS — set via environment variables (use setup-env.ps1 + .env file)
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION:ap-south-1}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}

#FFmpeg configurations
ffmpeg:
  path: ${FFMPEG_PATH:D:/PROJECT/NETFLIX/ffmpeg-8.1.2-essentials_build/bin/ffmpeg.exe}

#Temp dir for encoding
encoding:
  base-path: ${TEMP_DIR:D:/PROJECT/NETFLIX/temp/encoding}

#Actuators
management:
  endpoints:
    web:
      exposure:
        include: health,info
